version: '3'
services:
    apache:
        build: .docker/apache
        container_name: pmk_apache
        ports:
          - 8090:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/pmk
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: pmk_mysql
        ports:
            - 3308:3306
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pmk
            MYSQL_USER: pmk
            MYSQL_PASSWORD: pmk

    php:
        build: .docker/php
        container_name: pmk_php
        volumes:
          - .:/home/wwwroot/pmk
        environment:
          - maildev_host=pmk_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pmk_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8091:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: pmk_maildev
        ports:
          - 8092:80
